{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "devops-app.fullname" . }}
  labels:
    release: {{ .Values.monitoring.prometheusReleaseLabel | quote }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "devops-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}
{{- end }}
